sudo: false
language: node_js
node_js: lts/*
install:
- travis_retry gem install s3_website -v 3.4.0
- travis_retry pip install awscli --upgrade --user
- travis_retry npm install
script:
- npm run build
after_script:
- ./s3_deploy.sh
cache:
  bundler: true
  directories:
    - node_modules
